language: node_js

node_js:
  - "10.15.3"

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm run compile
  - npm test

script:
  - node sass
  - mkdir gh-pages
  - npm run doc.github
  - npm run doc.pokemon
  - npm run doc.shopify
  - npm run doc.starwars-js
  - npm run doc.starwars